[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
glob = "0.3.0"

[dev-dependencies]

[lib]
name = "leetcode"
path = "lib.rs"
doctest = false
